const test = require('node:test');
const assert = require('node:assert/strict');
const { callOpenAI, callAnthropic, callOpenRouter, extractOpenAIText, extractAnthropicText } = require('../scripts/provider-clients');
function res(status, data) { return { ok: status >= 200 && status < 300, status, json: async () => data, text: async () => JSON.stringify(data) }; }
test('extracts text from OpenAI Responses API payload', () => { assert.equal(extractOpenAIText({ output: [{ content: [{ type: 'output_text', text: '{"findings":[]}' }] }] }), '{"findings":[]}'); });
test('extracts text from Anthropic Messages payload while ignoring non-text blocks', () => { assert.equal(extractAnthropicText({ content: [{ type: 'thinking', thinking: 'x' }, { type: 'text', text: '{"findings":[]}' }] }), '{"findings":[]}'); });
test('OpenAI direct adapter uses Responses API and returns model metadata', async () => { const oldFetch = global.fetch; let seen; global.fetch = async (url, options) => { seen = { url: String(url), options }; return res(200, { output: [{ content: [{ type: 'output_text', text: '{"findings":[]}' }] }] }); }; try { const out = await callOpenAI('gpt-test', 'system', 'user', 5000, 'secret'); assert.equal(out.provider, 'openai'); assert.equal(out.model, 'gpt-test'); assert.equal(out.text, '{"findings":[]}'); assert.equal(seen.url, 'https://api.openai.com/v1/responses'); assert.match(seen.options.headers.Authorization, /^Bearer /); } finally { global.fetch = oldFetch; } });
test('Anthropic direct adapter uses Messages API and returns model metadata', async () => { const oldFetch = global.fetch; let seen; global.fetch = async (url, options) => { seen = { url: String(url), options }; return res(200, { content: [{ type: 'text', text: '{"findings":[]}' }] }); }; try { const out = await callAnthropic('claude-test', 'system', 'user', 5000, 'secret'); assert.equal(out.provider, 'anthropic'); assert.equal(out.model, 'claude-test'); assert.equal(out.text, '{"findings":[]}'); assert.equal(seen.url, 'https://api.anthropic.com/v1/messages'); assert.equal(seen.options.headers['x-api-key'], 'secret'); } finally { global.fetch = oldFetch; } });
test('provider rate limit remains fallback eligible for Hermes', async () => { const oldFetch = global.fetch; global.fetch = async () => res(429, { error: 'quota' }); try { await assert.rejects(() => callOpenRouter('m', 's', 'u', 5000, 'secret'), (err) => err.fallbackEligible === true && /HTTP 429/.test(err.message)); } finally { global.fetch = oldFetch; } });
